"""initial_schema

Revision ID: 7611f1d89eaa
Revises: 
Create Date: 2026-07-25 21:03:43.626174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7611f1d89eaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=255), nullable=True),
    sa.Column('brands', sa.JSON(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('atc_code', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('REVIEWER', 'SENIOR_REVIEWER', 'PV_LEAD', 'ADMIN', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.String(length=32), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=512), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('mesh_terms', sa.JSON(), nullable=False),
    sa.Column('publication_types', sa.JSON(), nullable=False),
    sa.Column('pubmed_url', sa.String(length=512), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('INGESTED', 'SCORED', 'ROUTED', 'UNDER_REVIEW', 'DEFERRED', 'SECOND_REVIEW', 'AUTO_CLEAR', 'QC_SAMPLE', 'DISPOSITION_NOT_CASE', 'DISPOSITION_VALID_ICSR', name='articlestatus'), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pmid', name='uq_articles_pmid')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_doi'), ['doi'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_pmid'), ['pmid'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_status'), ['status'], unique=False)

    op.create_table('export_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('article_ids', sa.JSON(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_strings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_strings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_strings_product_id'), ['product_id'], unique=False)

    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CONFIRM_NOT_CASE', 'CONFIRM_VALID_ICSR', 'OVERRIDE_AI', 'REQUEST_SECOND_REVIEW', 'DEFER_FULL_TEXT', 'RECALL_TO_REVIEW', name='decisionaction'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('identifiable_patient', sa.Boolean(), nullable=True),
    sa.Column('suspect_drug', sa.Boolean(), nullable=True),
    sa.Column('adverse_event', sa.Boolean(), nullable=True),
    sa.Column('identifiable_reporter', sa.Boolean(), nullable=True),
    sa.Column('seriousness', sa.String(length=64), nullable=True),
    sa.Column('listedness', sa.String(length=64), nullable=True),
    sa.Column('patient_age_range', sa.String(length=64), nullable=True),
    sa.Column('patient_sex', sa.String(length=32), nullable=True),
    sa.Column('patient_country', sa.String(length=64), nullable=True),
    sa.Column('event_terms', sa.JSON(), nullable=False),
    sa.Column('suspect_products', sa.JSON(), nullable=False),
    sa.Column('override_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_decisions_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('product_match', sa.Float(), nullable=False),
    sa.Column('event_relevance', sa.Float(), nullable=False),
    sa.Column('icsr_criteria_match', sa.Float(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('icsr_precheck', sa.JSON(), nullable=False),
    sa.Column('reason_tags', sa.JSON(), nullable=False),
    sa.Column('hard_rule_candidates', sa.JSON(), nullable=False),
    sa.Column('summary_for_reviewer', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('threshold_version', sa.String(length=64), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_results_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_composite'), ['composite'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_string_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='searchrunstatus'), nullable=False),
    sa.Column('query_snapshot', sa.Text(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('new_article_count', sa.Integer(), nullable=False),
    sa.Column('rehit_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response_hash', sa.String(length=64), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['search_string_id'], ['search_strings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_runs_search_string_id'), ['search_string_id'], unique=False)

    op.create_table('article_appearances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('is_first_seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_appearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_appearances_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_appearances_search_run_id'), ['search_run_id'], unique=False)

    op.create_table('triage_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('screening_result_id', sa.Integer(), nullable=False),
    sa.Column('queue', sa.Enum('AUTO_CLEAR', 'STANDARD', 'PRIORITY', 'EXPEDITED', 'QC_SAMPLE', name='queuetype'), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hard_rule_triggered', sa.Boolean(), nullable=False),
    sa.Column('hard_rules', sa.JSON(), nullable=False),
    sa.Column('ruleset_version', sa.String(length=64), nullable=False),
    sa.Column('threshold_version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['screening_result_id'], ['screening_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_assignments_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_assignments_queue'), ['queue'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_assignments_screening_result_id'), ['screening_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_assignments_sla_due_at'), ['sla_due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triage_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_assignments_sla_due_at'))
        batch_op.drop_index(batch_op.f('ix_triage_assignments_screening_result_id'))
        batch_op.drop_index(batch_op.f('ix_triage_assignments_queue'))
        batch_op.drop_index(batch_op.f('ix_triage_assignments_article_id'))

    op.drop_table('triage_assignments')
    with op.batch_alter_table('article_appearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_appearances_search_run_id'))
        batch_op.drop_index(batch_op.f('ix_article_appearances_article_id'))

    op.drop_table('article_appearances')
    with op.batch_alter_table('search_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_runs_search_string_id'))

    op.drop_table('search_runs')
    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_results_composite'))
        batch_op.drop_index(batch_op.f('ix_screening_results_article_id'))

    op.drop_table('screening_results')
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_decisions_article_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('search_strings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_strings_product_id'))

    op.drop_table('search_strings')
    op.drop_table('export_packages')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_status'))
        batch_op.drop_index(batch_op.f('ix_articles_product_id'))
        batch_op.drop_index(batch_op.f('ix_articles_pmid'))
        batch_op.drop_index(batch_op.f('ix_articles_doi'))

    op.drop_table('articles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('products')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
